# Generated by Django 4.1.5 on 2023-03-07 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('idadmin', models.AutoField(primary_key=True, serialize=False)),
                ('admin_no', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'admin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('idsite', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'site',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Site_Ad',
            fields=[
                ('idSA', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'site_ad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Us',
            fields=[
                ('idus', models.AutoField(primary_key=True, serialize=False)),
                ('e_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'us',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('iduser', models.AutoField(primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=11)),
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
